### ISSUE TITLE
Trainer details are not displayed

### ISSUE THREAD

**Issue by SHAMPHAVI** [bistecglobal/blockchain-certificates-issuer#137]
![image](https://github.com/bistecglobal/blockchain-certificates-issuer/assets/30856796/c2de700b-5bcf-4d2a-9748-af9a3d7b6e53)

**Comment by gishann** [comment]
@SHAMPHAVI This issue is fixed now. Therefore closing this issue.
![image](https://github.com/bistecglobal/blockchain-certificates-issuer/assets/32861524/89181c45-631f-48c7-8ec3-eb02b9c24bca)
